--- 
- name: CVMFS
  hosts: localhost
  become: true
  vars:
    cvmfs_role: client
    galaxy_cvmfs_repos_enabled: config-repo
    la_cvmfs_repository: data.elixir-italy-cvmfs 
  roles:
    - geerlingguy.repo-epel
    - galaxyproject.cvmfs
  post_tasks:

    - name: download elixir-italy-cvmfs config
      get_url:
        url: 'https://raw.githubusercontent.com/indigo-dc/Reference-data-galaxycloud-repository/master/{{ item.conf_file }}/{{ la_cvmfs_repository}}.{{ item.ext }}'
        dest: '/etc/cvmfs/{{ item.dest_dir }}/{{ la_cvmfs_repository}}.{{ item.ext }}'
      with_items: 
        - { conf_file: cvmfs_server_config_files , dest_dir: config.d , ext: conf} 
        - { conf_file: cvmfs_server_keys , dest_dir: keys , ext: pub  } 
    
    - name: probe elixir cvmfs
      shell:
        cmd: 'cvmfs_config probe {{ la_cvmfs_repository}}'


